apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  # scrape itself + any ServiceMonitors you create
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vminsert-vmcluster.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
